"""users table pash

Revision ID: 97b26e5cd7a8
Revises: a64a79dff999
Create Date: 2020-06-22 04:45:48.866385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b26e5cd7a8'
down_revision = 'a64a79dff999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_has', sa.String(length=140), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_has')
    # ### end Alembic commands ###
